# Generated by Django 4.0.4 on 2022-04-20 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("xmlreader", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="upload",
            old_name="filename",
            new_name="file",
        ),
    ]
